#!/usr/bin/env bash

# Install ufw if not already installed
sudo apt-get update
sudo apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp     # SSH
sudo ufw allow 443/tcp    # HTTPS
sudo ufw allow 80/tcp     # HTTP

# Enable ufw
sudo ufw --force enable

# Check ufw status
sudo ufw status verbose
